### ISSUE TITLE
`@keyframes` get compressed, causing sync issues with the animation-name CSS property

### ISSUE THREAD

**Issue by FabulousCodingFox** [RodrigoTomeES/astro-rename#20]
It seems like `@keyframes` animations are being compressed (specifically the name of the keyframes), but their corresponding references in the animation-name directive within the CSS are not being similarly compressed. This results in a mismatch where the animation is not applied as intended.

For example, in the following CSS:
```css
.g[data-astro-cid-wxwyi4a4] {
  animation-name: popup;
  animation-duration: .75s;
  animation-fill-mode: forwards;
  animation-timing-function: ease-out;
  will-change: transform, opacity;
}

@keyframes g { /*  Shoud be @keyframes popup { */
  0% {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
```
